# Generated by Django 4.1.10 on 2023-08-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.CharField(max_length=50)),
                ('check_out', models.CharField(max_length=50)),
                ('adults', models.CharField(max_length=50)),
                ('childs', models.CharField(max_length=50)),
                ('rooms', models.CharField(max_length=50)),
            ],
        ),
    ]
